version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v3
  backend_user:
    build:
      context: ./udagramuserservice
    image: udagram-api-userservice:v3
  backend_gratitude:
    build:
      context: ./udagramgratitudeservice
    image: udagram-api-gratitude:v3
